image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: TreeCalculator\TreeCalculator.sln
  - solution_path: GenericList\GenericList\GenericList.sln
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
