image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: sort_array\sort_array.sln  
  - solution_path: 2.1\2.1.sln
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
