image: Visual Studio 2017

environment:
  
  matrix:
  - solution_path: TreeCalculator_with_OOP\TreeCalculator\TreeCalculator.sln
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
